### ISSUE TITLE
Cannot put Attack Badges on Unlocked Characters by the tool.

### ISSUE THREAD

**Issue by AngelSora** [nedron92/HWL-SaveEditor#1]
The title say Everything.

**Comment by nedron92** [comment]
Thanks for the information, don't even know that. 
I did some research and found the problem, there is a ingame-flag which let you put the Attack-Badge on a new unlocked character. I will fix that in few days. (2-3)

**Comment by AngelSora** [comment]
Thanks, i appreciate it. ;)

**Comment by nedron92** [comment]
It's fixed now :), try the nightly build (have start it manually), https://nightly.nedron92.php-friends.de/hwl_save-editor/ . 
I will make an direct new release after I found out needed weapon-things for Medili (Update 1.3.0).

**Comment by AngelSora** [comment]
Tested. (At my own risk) I can finally put badges. BUT ONLY ON THE FIRST WEAPONS ! Other weapons slots are gone, even those i unlocked...

**Comment by nedron92** [comment]
Okay, that's weired. Can you describe exactly what you have done? 
What you mean exactly, you can only put an Attack-Badge to the first Attack-Badge-Slot? Or? 
Can you put your savefiles in a zip and attached here? I have to compare some offsets within the files. 
(Unmodified and modified, hopefully you have an original backup?)

**Comment by AngelSora** [comment]
When you unlocked a new Weapon for Link, (Example: Fire Rod, Epona, Gauntlet, Great Fairy.) You are suppose to have new slot of Attack Badges based on the Weapons Combos. I have unlocked some just to get these slot. Then, i tested your Nightly Build and... The first weapon Combo Badges are still here. But the other weapons combo slots are GONE ! So, the only good thing that miss with that program is... add the rest of missing badges. Even in the biggining of the game. I hope that help. ;)

**Comment by nedron92** [comment]
Thanks for the info, I will search and fix it, if I have time, but nothing expected before next tuesday, cause of personally reasons.

**Comment by nedron92** [comment]
A long is passed, but I worked on the editor in the last weeks ;) 
I changed many core things and added full support till Update 1.6.0 and 4th DLC. 
I clean the code and tried some minutes ago the current version, unlocked a character and all badges can be attached. Hopefully it is also fixed on your site. 
EDIT: I finally really fixed it, you cann now attached also the other weapon-badges

Can you download the newest nightly-version (V.2.9.6.0) and give me a new feedback if the failure is beeing away? :) 
https://nightly.nedron92.php-friends.de/hwl_save-editor/

Thanks again, @AngelSora
