### ISSUE TITLE
Weapon modding goes to the wrong character

### ISSUE THREAD

**Issue by KaraNoelle** [nedron92/HWL-SaveEditor#3]
Modifying weapons through the GUI and saving them shifts them over to other characters. For example, I've modified Cia's Scepter only to have it go to Ganon's Greatswords. I then modified a set of Ganon's Greatswords and they go to Zelda's Dominion Rod. However, when I set the character's levels and stats, it sets them properly.

**Comment by nedron92** [comment]
Fixed with version 3.2a, newest merge into master #4
